version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_DB=db
    volumes:
      - postgres_data1:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Проброс портов (внешний:внутренний)
    networks:
      - net

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    networks:
      - net

  rabbitmq:
    image: rabbitmq:3.10.7-management
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - net

  auth:
    image: auth
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_started
      minio:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - net

  post:
    image: post
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_started
      minio:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - net

  subscr:
    image: subscr
    ports:
      - "8002:8002"
    depends_on:
      db:
        condition: service_started
      minio:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - net

  admin:
    image: admin
    ports:
      - "8003:8003"
    depends_on:
      db:
        condition: service_started
      minio:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - net

# для тестов
  test-db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=test-user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db
    ports:
      - 5434:5432 # # Проброс портов (внешний:внутренний)
    expose:
      - "5434"
    volumes:
      - test-db-data:/var/lib/postgresql/data:cached

  test-minio:
    image: minio/minio
    ports:
      - "9004:9000"
      - "9005:9001"
    expose:
      - "9004"
    volumes:
      - ./minio_test/data:/data
    environment:
      MINIO_ROOT_USER: testminioadmin
      MINIO_ROOT_PASSWORD: testminioadmin
    command: server --console-address ":9004" /data
    networks:
      - net

volumes:
  postgres_data1:
  test-db-data:

networks:
  net:
    driver: bridge
