"""add_photo_column

Revision ID: 4953a3fe0341
Revises: d2c0e9c6163b
Create Date: 2025-03-24 07:55:20.448466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4953a3fe0341'
down_revision: Union[str, None] = 'd2c0e9c6163b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'text',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.add_column('post', sa.Column('text', sa.String(length=300), nullable=False))
    op.drop_column('post', 'filename')
    op.add_column('user', sa.Column('photo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'photo')
    op.add_column('post', sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('post', 'text')
    op.alter_column('comment', 'text',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
    # ### end Alembic commands ###
